### ISSUE TITLE
Glitch on contact button on Chrome

### ISSUE THREAD

**Issue by acorbi** [OpenDevelopmentMekong/wp-odm_user_feedback#29]
Tested with chrome Version 58.0.3029.81 (64-bit) in Ubuntu linux

On https://opendevelopmentcambodia.net/

![screenshot from 2017-04-26 10-51-19](https://cloud.githubusercontent.com/assets/384894/25426075/4dcc4344-2a6e-11e7-898a-751f80a60b97.png)

@Huyeng can you reproduce this?

**Comment by Huyeng** [comment]
I don't use the Ubuntu linux, but it looks fine on Mac. 
Could you try to refresh with clearing the browser's catch? I think that something may wrong with the CSS.

**Comment by Huyeng** [comment]
@acorbi-  is the issue still happening?

**Comment by acorbi** [comment]
Looks fine now, closing
