### ISSUE TITLE
contact us button hides important controls on maps

### ISSUE THREAD

**Issue by acorbi** [OpenDevelopmentMekong/wp-odm_user_feedback#8]
Oin thematic maps, such as https://opendevelopmentmekong.net/maps/aqueduct-atlas/, the **Contact us** button blocks important functionality.

![screenshot from 2017-03-22 09-17-43](https://cloud.githubusercontent.com/assets/384894/24188189/b54f7918-0ee0-11e7-9c1f-a997151f4c89.png)

**Comment by Huyeng** [comment]
@acorbi , Any suggestion on this?

**Comment by acorbi** [comment]
@Huyeng my preference would be to have that button on the header, close to the contact/social buttons:

![screenshot from 2017-03-23 11-38-59](https://cloud.githubusercontent.com/assets/384894/24243974/5fd8e5ea-0fbd-11e7-8f28-13204629f98a.png)

It would be less prominent but at least would not cause this kind of issues. Also would be consistent with https://github.com/OpenDevelopmentMekong/wp-odm_user_feedback/issues/7 since it would not be necesseray to hide the button on mobile anymore.

**Comment by Huyeng** [comment]
The email icon is used for subscription on ODC site. I would like to use the narrow icon to be able to hide and show, what do you this?

**Comment by acorbi** [comment]
We can add another icon (example: http://fontawesome.io/icon/bullhorn/)

> I would like to use the narrow icon to be able to hide and show, what do you this?

what icon is that? Again, my preference is to put that button on the header. the reason is that:

1. Header is always visible in both desktop and mobile devices
2. Header does not conflict with the content

**Comment by Huyeng** [comment]
I would like to add the collapsed and expended icon as below:
- Hide the contact us button on click: 
![screenshot_4](https://cloud.githubusercontent.com/assets/6613530/24292009/01028bdc-10be-11e7-93cf-9cda6e4e9642.jpg)

- Show the contact button on click:
![screenshot_5](https://cloud.githubusercontent.com/assets/6613530/24292022/0c73a3a2-10be-11e7-8bbe-c834bb6ed7a0.jpg)
